# Generated by Django 5.1.1 on 2024-09-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/user-default.png', null=True, upload_to='static/images'),
        ),
    ]
