# Generated by Django 5.1.1 on 2024-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.tag'),
        ),
    ]
